name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Build
        run: poetry build --format wheel
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
          $(ls -d -1 "$PWD/dist/"*.*)#Wheel \
          --repo="$GITHUB_REPOSITORY" \
          --title="${tag#v}" \
          --generate-notes